name: PygBag build

on: [push]

jobs:
  pygbag-build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run pygbag build
        run: uvx pygbag --build .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pygbag-build-artifacts
          path: build/web
          if-no-files-found: error
