name: PygBag build

on: [push]

jobs:
  pygbag-build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get the build information
        id: build_info
        uses: chuhlomin/render-template@v1
        with:
          template: build_info.py
          result_path: build_info.py
          vars: |
            build_info: ${{ github.sha }} ${{ github.run_number }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run pygbag build
        run: uvx pygbag --template page/main.tmpl --build --ume_block=0 .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pygbag-build-artifacts
          path: build/web
          if-no-files-found: error

      - name: Upload build artifacts to GitHub Pages
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/web

  gh-deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: pygbag-build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
